baseURL = "https://hjwu.github.io/"
languageCode = "zh-Hans"
theme = "moments"

[pagination]
pagerSize = 8
path = "page"

[markup]
[markup.highlight]
codeFences = true
lineNos = true
lineNumbersInTable = false
style = "pastie"
tabWidth = 4

[params]
title = "ðŸŒˆ é™³é¦¬å°¼ æˆ‘æƒ³ä½ "
signature = "I Love You 8128 times"
# cover = "https://cdn.pixabay.com/photo/2018/03/13/22/53/puzzle-3223941_1280.jpg"

# name = "Moments ä¸»é¢˜"
# avatar = "moment-avatar.png"

infiniteScroll = false

[params.features]
pangu = true

[params.experimental]
comment = false
